"""Add denormalized columns

Revision ID: 15b4e3c55e9e
Revises: 001
Create Date: 2026-04-11 22:32:56.710646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '15b4e3c55e9e'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('total_vendas', sa.Integer(), server_default='0', nullable=False))
    op.add_column('produtos', sa.Column('preco_medio', sa.Float(), nullable=True))
    op.add_column('produtos', sa.Column('total_avaliacoes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('produtos', sa.Column('avaliacao_media', sa.Float(), nullable=True))
    op.execute("""
        UPDATE produtos
        SET
            total_vendas = COALESCE((
                SELECT COUNT(id_item)
                FROM itens_pedidos
                WHERE id_produto = produtos.id_produto
            ), 0),
            preco_medio = (
                SELECT AVG(preco_BRL)
                FROM itens_pedidos
                WHERE id_produto = produtos.id_produto
            )
    """)

    op.execute("""
        UPDATE produtos
        SET
            total_avaliacoes = COALESCE((
                SELECT COUNT(ap.id_avaliacao)
                FROM avaliacoes_pedidos ap
                JOIN pedidos p ON p.id_pedido = ap.id_pedido
                JOIN itens_pedidos ip ON ip.id_pedido = p.id_pedido
                WHERE ip.id_produto = produtos.id_produto
            ), 0),
            avaliacao_media = (
                SELECT AVG(ap.avaliacao)
                FROM avaliacoes_pedidos ap
                JOIN pedidos p ON p.id_pedido = ap.id_pedido
                JOIN itens_pedidos ip ON ip.id_pedido = p.id_pedido
                WHERE ip.id_produto = produtos.id_produto
            )
    """)# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'avaliacao_media')
    op.drop_column('produtos', 'total_avaliacoes')
    op.drop_column('produtos', 'preco_medio')
    op.drop_column('produtos', 'total_vendas')
    op.create_index('idx_item_produto', 'itens_pedidos', ['id_produto'], unique=False)
    op.create_index('idx_item_pedido', 'itens_pedidos', ['id_pedido'], unique=False)
    op.create_index('idx_avaliacao_pedido', 'avaliacoes_pedidos', ['id_pedido'], unique=False)
    # ### end Alembic commands ###
