"""Add Usuarios

Revision ID: b0d89c19605d
Revises: 9437b52b16f8
Create Date: 2026-04-11 23:09:23.528993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b0d89c19605d'
down_revision: Union[str, None] = '9437b52b16f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'usuarios',
        sa.Column('id_usuario', sa.String(length=32), nullable=False),
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id_usuario'),
    )
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
